name: Citra build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: submodules
      run: git submodule update --init --recursive
    - name: install-qt6
      run: sudo apt install qt6-base-dev qt6-base-private-dev qt6-multimedia-dev
    - name: install-sld2
      run: sudo apt install libsdl2-dev
    - name: install-openssl
      run: sudo apt install libssl-dev
    - name: install-audio
      run: sudo apt install libasound-dev
    - name: Install Vulkan SDK
  # You may pin to the exact commit or the version.
  # uses: humbletim/install-vulkan-sdk@6aadcb709dbb8e4096dad20e35adaefec83d4b45
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
    # official Vulkan SDK release version to use
        version: latest # default is latest
    # whether to cache the downloaded vulkan_sdk.* installer file (using github actions/cache)
        cache: yes # optional
    # silence GitHub Annotation notice displayed if resolving `latest` into Vulkan SDK release number
        quiet: true # optional
    - name: make
      run: cmake .
